// Generated by CoffeeScript 1.6.3
var config;

config = {
  filename: __filename,
  ns: 'ui2',
  scripts: {
    modal: require('./modal')
  },
  styles: [__dirname]
};

module.exports = function(app, options) {
  app.fn('ui.modal.create', function(modal) {
    var name;
    name = modal.model.get('name');
    if (name) {
      app.fn("modal." + name + ".show", function() {
        this.model.set("_page.modal." + name, true);
        return modal.show();
      });
      return app.fn("modal." + name + ".close", function(e) {
        var action;
        action = e.target.getAttribute("data-action");
        console.log('close, action = ' + action);
        this.model.pass({
          action: action
        }).del("_page.modal." + name);
        return modal.close(action);
      });
    }
  });
  return app.createLibrary(config, options);
};
