// Generated by CoffeeScript 1.6.3
var config;

config = {
  filename: __filename,
  ns: 'ui2',
  scripts: {
    modal: require('./modal')
  },
  styles: [__dirname]
};

module.exports = function(app, options) {
  app.fn('ui.modal.create', function(modal) {
    var name;
    name = modal.model.get('name');
    if (name) {
      app.fn("modal." + name + ".show", function() {
        return modal.show();
      });
      return app.fn("modal." + name + ".close", function() {
        return modal.close();
      });
    }
  });
  return app.createLibrary(config, options);
};
