// Generated by CoffeeScript 1.6.3
exports.create = function(model, dom) {
  var self;
  self = this;
  return dom.addListener(document, "keydown", function(e) {
    console.log('keydown');
    if (model.get('keydown') && model.get('show')) {
      console.log('keydown - closing');
      console.log(self);
      if (e.keyCode === 27) {
        return self.close("escape");
      }
    }
  });
};

exports.show = function() {
  return this.model.set("show", true);
};

exports.close = function(action) {
  return this.model.set("show", false);
};
