// Generated by CoffeeScript 1.6.3
exports.create = function(model, dom) {
  var self;
  self = this;
  if (model.get('keydown')) {
    return dom.addListener(document, "keydown", function(e) {
      if (e.keyCode === 27) {
        return self.close("escape");
      }
    });
  }
};

exports.show = function() {
  return this.model.set("show", true);
};

exports.close = function(action) {
  var cancelled;
  cancelled = this.emitCancellable("close", action);
  if (!cancelled) {
    return this.model.set("show", false);
  }
};

exports._click = function(e) {
  var action;
  action = e.target.getAttribute("data-action");
  if (action) {
    return this.close(action);
  }
};
