// Generated by CoffeeScript 1.6.3
exports.create = function(model, dom) {
  var self;
  self = this;
  if (model.get('keydown')) {
    return dom.addListener(document, "keydown", function(e) {
      if (e.keyCode === 27) {
        return self.close("escape");
      }
    });
  }
};

exports.show = function() {
  return this.model.set("show", true);
};

exports.close = function(action) {
  console.log('closing, action = ' + action);
  return this.model.set("show", false);
};
